spring:
  datasource:
    url: jdbc:mysql://118.126.111.144:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 8088
